# Generated by Django 5.2.6 on 2025-09-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='live',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='tested',
            field=models.CharField(max_length=100),
        ),
    ]
