# Generated by Django 5.2.6 on 2025-09-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_task_live_alter_task_tested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='live',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='tested',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
